name: push
on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Use Node.js 14.x
        with:
          node-version: 14.x
        uses: actions/setup-node@v3
        
      - name: Install npm dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Use Node.js 14.x
        with:
          node-version: 14.x
        uses: actions/setup-node@v3

      - name: Install npm dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Run coverage
        run: npm run test:cov
  sonar:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Use Node.js 14.x
        with:
          node-version: 14.x
        uses: actions/setup-node@v3

      - name: Install npm dependencies
        run: npm ci
      - name: SonarCloud Scan
        env:
            GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
            SONAR_TOKEN: ${{ secrets.TOKEN_SONAR }}
        uses: sonarsource/sonarcloud-github-action@master
        